server:
  port: 6001

eureka:
  instance:
    hostname: eureka6001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:6002/eureka/
